services:
  votebot:
    build:
      context: .
    command: python manage.py app
    volumes:
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      votebotdb:
        condition: service_healthy
    restart: always

  votebotweb:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: djangovote
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      votebotdb:
        condition: service_healthy
    restart: always

  votebotdb:
    image: postgres:13
    container_name: postgresvote
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votes
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:

    